// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhlB5LHa9DFfjRJu1SG-n8UuO_I1zbuDU',
    appId: '1:708068745033:web:9c4a276f6c212cbecdc498',
    messagingSenderId: '708068745033',
    projectId: 'pureblog-7d249',
    authDomain: 'pureblog-7d249.firebaseapp.com',
    databaseURL: 'https://pureblog-7d249-default-rtdb.firebaseio.com',
    storageBucket: 'pureblog-7d249.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsUhOgIFRt8-8-tLLWgEAK7llTBX_3Ns',
    appId: '1:708068745033:android:ef36842aa1b49ae8cdc498',
    messagingSenderId: '708068745033',
    projectId: 'pureblog-7d249',
    databaseURL: 'https://pureblog-7d249-default-rtdb.firebaseio.com',
    storageBucket: 'pureblog-7d249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC72mH9Dn4EpYgOH6JvPji1XbrcllXWMyY',
    appId: '1:708068745033:ios:5183da71e17ed45bcdc498',
    messagingSenderId: '708068745033',
    projectId: 'pureblog-7d249',
    databaseURL: 'https://pureblog-7d249-default-rtdb.firebaseio.com',
    storageBucket: 'pureblog-7d249.appspot.com',
    iosClientId: '708068745033-dtukul77ic2v2vfmqfsd2ta9rahdkm9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC72mH9Dn4EpYgOH6JvPji1XbrcllXWMyY',
    appId: '1:708068745033:ios:5183da71e17ed45bcdc498',
    messagingSenderId: '708068745033',
    projectId: 'pureblog-7d249',
    databaseURL: 'https://pureblog-7d249-default-rtdb.firebaseio.com',
    storageBucket: 'pureblog-7d249.appspot.com',
    iosClientId: '708068745033-dtukul77ic2v2vfmqfsd2ta9rahdkm9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureBlog',
  );
}
